### ISSUE TITLE
[NEW] PHP Switch Operator

### ISSUE THREAD

**Issue by rendzzx** [khumam/fastcard#2]
**Category**
PHP

**Title**
Switch Operator

**Description**
The switch operator in PHP is a control flow statement that allows you to execute different code blocks based on the value of an expression. It is similar to a series of if-else statements, but it can be more efficient for comparing the same expression to multiple values.

**Cards**
To use the switch operator, you first need to define a variable or expression to be evaluated. Then, you use the switch statement to compare the value of the variable or expression to a list of case statements. If the value matches one of the case statements, the code block associated with that case statement is executed. If the value does not match any of the case statements, the default code block (if it exists) is executed.

## Card 01: Switch Operator
```php
<?php

$color = "red";

switch ($color) {
    case "red":
        echo "The color is red.";
        break;
    case "green":
        echo "The color is green.";
        break;
    case "blue":
        echo "The color is blue.";
        break;
    default:
        echo "The color is unknown.";
}
// output: The color is red.
?>
```

**Comment by khumam** [comment]
Added to PHP card. The new card it should be the main title for specific term in programming. So because it is in PHP I added to PHP section.

Thank you 🍻
